_target_: pytorch_lightning.Trainer

gpus: 0

min_epochs: 1
max_epochs: 10

progress_bar_refresh_rate: 5
resume_from_checkpoint: null
weights_summary: "full"

# execute 2 validation steps for sanity check
num_sanity_val_steps: 2
